package:
    name:           yii2-x-editable
    namespace:      xeditable
    label:          X-editableExtension
    title:          X-editable extension for Yii2
    type:           yii2-extension
    forum:          https://forum.hiqdev.com/yii2
    keywords:       x-editable, widget, editable column, extension, yii2
    description:    X-editable extension for Yii2 with Widget, EditableColumn and so on
    year:           2015

require:
    hiqdev/hidev-config-php:    "*@dev"
